# Generated by Django 4.2.7 on 2023-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorid', models.CharField(max_length=255)),
                ('patientid', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('emergency', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='patentdata',
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
