# Generated by Django 4.2.7 on 2023-11-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0007_remove_userdata_otp'),
        ('aerodevice', '0002_patientdata_delete_patentdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='userid',
            new_name='device_name',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='assignuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerouser.userdata'),
        ),
    ]
