# Generated by Django 4.2.7 on 2023-11-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0007_remove_userdata_otp'),
        ('aerodevice', '0003_rename_userid_devicedata_device_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerodevice.devicedata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerouser.userdata')),
            ],
        ),
    ]
