# Generated by Django 4.2.7 on 2023-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevice', '0004_usermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='patientdata',
            name='admitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='blood',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='bmi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='deviceid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='ibw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='itv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='potential',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='doctorid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='emergency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patientid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
