# Generated by Django 4.2.7 on 2023-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevice', '0006_remove_patientdata_admitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='admitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
