# Generated by Django 4.2.7 on 2023-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevice', '0007_patientdata_admitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='battery_mfd_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='battery_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='lot_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='mac',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='mfd_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='device_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='blood',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='bmi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='deviceid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='doctorid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='emergency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='ibw',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='itv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patientid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='potential',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
