# Generated by Django 4.2.7 on 2023-12-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevice', '0008_devicedata_battery_mfd_date_devicedata_battery_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='model_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
