# Generated by Django 4.2.7 on 2023-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
