# Generated by Django 4.2.7 on 2023-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0003_rename_firstname_userdata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
