# Generated by Django 4.2.7 on 2023-11-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0006_userdata_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='otp',
        ),
    ]
