# Generated by Django 4.2.7 on 2023-12-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerouser', '0007_remove_userdata_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='usertype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
